added country config
BustByte/coronastatus.no pull request #237
Opened 2020-03-22 19:16 UTC by zacel

my local env is rewriting the locale files whenever I start the server to test but everything is setup and looks good

2020-03-22 19:22 UTC, adriaandotcom requested changes
Two little things

2020-03-22 19:22 UTC, adriaanvanrossum commented on app/views/pages/report.ejs
> +            <%= __('Are you from ') + __(locals.country) + "? "%>
I would remove the spacing from the translation and add it in the HTML.

2020-03-22 19:22 UTC, adriaanvanrossum commented on app/locales/nl.json
> +	"Netherlands":"Nederland",
Oops, tabs here!

2020-03-22 19:23 UTC, zacel commented
Ok will fix these things now

2020-03-22 19:27 UTC, fossecode commented
https://github.com/mashpie/i18n-node/issues/266

> Root cause could be any error in you scripts and/or json files. Please ensure that you json files are valid to strict json specs, like using " and not ', don't have trailing commas or comments.

> One possible scenario might be: A wrong typed json file get's read by i18n. An empty locale object get's initiated due to json-parsing-errors and as soon any i18n.__() get invoked i18n writes back a new json file but with freshly initiated object containing keys only.

> The config setting will safe you from destroying your data. But i18n might not work until you fix the root cause of that error.

2020-03-22 19:28 UTC, fossecode commented
We could consider setting the following in the i18n config:
```
updateFiles: false
```

2020-03-22 19:29 UTC, fossecode approved these changes

2020-03-22 19:29 UTC, zacel commented
Ok thank you fossecode. Maybe it was the trailing commas. My mistake I thought we were supposed to do that still as it was said to do yesterday

2020-03-22 19:47 UTC, adriaandotcom approved these changes

2020-03-22 19:59 UTC, adriaanvanrossum commented
```
updateFiles: false
```

would be great I think

2020-03-22 19:59 UTC, merged

2020-08-15 15:30 UTC, mashpie commented
Hi there! Author of `i18n` here... if you need any help with implementation, just drop me a line! 

`updateFiles: false` will be default in an upcoming release