[WIP] Add remaining data for the SK launch
BustByte/coronastatus.no pull request #263
Opened 2020-03-23 20:01 UTC by sbocinec

#256

2020-03-23 20:58 UTC, fossecode commented on app/views/pages/nl-lang-privacy-policy.ejs
> -            href="https://simpleanaltyics.io" target="_blank">Simple Analytics</a>
Good catch!

2020-03-23 21:01 UTC, fossecode commented
I don't know slovak, but other than that it looks good! 😄Could you add an image to be used on social media when people share the site? Should be located in `/static/sk/social1.png`

2020-03-23 21:01 UTC, fossecode approved these changes

2020-03-23 21:51 UTC, fossecode commented
Ready to merge? :)

2020-03-23 22:13 UTC, sbocinec commented
> Ready to merge? :)

no no, it's an early draft yet, WIP :-) I will need to properly go through all the views in the app and I expect there are lot of mistakes and inaccurate translations. Also the privacy policy needs some tweaking, etc... So please ignore this PR until i remove the `[WIP]` prefix (i forgot to create this as a draft PR :-| ). Thank you!

2020-03-23 22:14 UTC, fossecode reviewed
Will review again when it is no longer WIP

2020-03-24 11:22 UTC, adriaanvanrossum commented
Fixed your merge conflict

2020-03-24 20:01 UTC, adriaandotcom requested changes

2020-03-24 20:01 UTC, adriaanvanrossum commented on app/views/pages/nl-lang-privacy-policy.ejs
> +  <a href="https://simpleanalytics.io" class="text-cvs-red hover:underline" target="_blank">Simple Analytics</a>
It's `https://simpleanalytics.com` actually

2020-03-24 20:01 UTC, adriaanvanrossum commented on app/views/pages/sk-lang-privacy-policy.ejs
> +<!DOCTYPE html>
Oops. Please copy the format of the other privacy policy pages. The header and footer did change!

2020-03-26 09:32 UTC, Kilian approved these changes

2020-03-26 09:33 UTC, Kilian commented
I'm overwriting @adriaanvanrossum review and pressing the merge button. The review has no changes requested anymore but Github didn't pick that up.

2020-03-26 09:33 UTC, merged

2020-03-26 09:34 UTC, adriaanvanrossum commented
Perfect