Telegram bot which (currently) let's us deploy sites
BustByte/coronastatus.no pull request #555
Opened 2020-04-05 15:30 UTC by michaelmcmillan

2020-04-05 18:04 UTC, fossecode approved these changes

2020-04-05 19:20 UTC, adriaandotcom requested changes

2020-04-05 19:20 UTC, adriaanvanrossum commented on ops/bot/bot.ts
> +  'coronastatus.it': 'app@coronastatus.it /srv/scripts/deploy-prod.sh',
Shouldn't be all websites here?

2020-04-16 17:35 UTC, adriaandotcom approved these changes

2020-04-16 17:35 UTC, merged

2020-04-16 18:19 UTC, fossecode commented
Not sure if this one works anymore

2020-04-16 18:57 UTC, adriaanvanrossum commented
can we test in the telegram group?